
  name: tuxtron
  version: '1.1'
  summary: Tests and improves the security of Linux machine
  description: |
      Built with the security conscious hobbyists or full blown information security professionals in mind, this tool is aimed at helping you ensure your Linux system is 
      secure by checking your firell, antivirus software, local configurations and updates are all in check including Port scanning on your WAN IP, performing an in depth 
      Lynis audit and more. This script is open source, and will be built upon by the Linux community in the future.

  grade: stable # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  parts:
    my-part:
      # See 'snapcraft plugins'
      plugin: nil
  
